version: '3.3'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
        - 6379:6379

  pastebin:
    build:
      context: .
      dockerfile: Dockerfile
    image: pastebin
    container_name: pastebin
    command: node_modules/.bin/nodemon api/index.js
    ports:
      - "8080:8080"
    volumes:
      - .:/home/node/app
      # - node_modules:/home/node/app/node_modules
    restart: always

# volumes:
#   node_modules:  